language: php
dist: xenial

php:
- 7.0
- 7.1
- 7.2
- 7.3
- nightly

matrix:
  allow_failures:
  - php: nightly

cache:
  directories:
  - $HOME/.composer/cache/files
  - vendor

install:
- composer install --prefer-dist

script:
- composer run cs-check
- composer run coverage-clover

after_script:
- php vendor/bin/codacycoverage clover build/coverage/clover.xml
