language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

before_install:
  - composer install

script:
  - composer run cs-check
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml

after_script:
  - php vendor/bin/codacycoverage clover build/coverage/xml
